### ISSUE TITLE
some base class methods missing from FDPF

### ISSUE THREAD

**Issue by andyj115** [Setasign/FPDI-tFPDF#1]
for example

    function GetPageWidth() {
        // Get current page width
        return $this->w;
    }

    function GetPageHeight() {
        // Get current page height
        return $this->h;
    }

thank you, Andy

**Comment by JanSlabon** [comment]
tFPDF is based on FPDF 1.7 where these properties are simply public.

You opened the issue in this package, which has no code at all but is a metadata-only repo.
[This](https://github.com/Setasign/tfpdf) would be the more correct one but there's no development done:
> This repository is only made for cloning official tFPDF releases which are available at: http://fpdf.org/en/script/script92.php THERE WILL BE NO DEVELOPMENT IN THIS REPOSITORY!
